apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ju7tfiy9b-dotnet-basic
  janus-idp.io/tekton: ju7tfiy9b-dotnet-basic
  backstage.io/kubernetes-id: ju7tfiy9b-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ju7tfiy9b-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
